### ISSUE TITLE
Numbering Incorrect in the About page

### ISSUE THREAD

**Issue by bollimuntha-shreya** [IIITH-Resources/iiith-resources.github.io#1]
![image](https://user-images.githubusercontent.com/97241745/150292863-e49a55b4-3bb0-466e-bb96-a302a17cd251.png)

**Comment by bhavberi** [comment]
Actually, initially I didn't numbered myself.
And moreover, i wanted to start numbering from 0. So didn't numbered myself afterwards.
So, please once confirm all @IIITH-Resources/cxx-content-team  @IIITH-Resources/ecx-content-team , that you wanted numbering to start from 1.... or 0.... And will update it as majority.

**Comment by bhavberi** [comment]
/polls Numbering from 0 'Numbering from 1'

**Comment by bhavberi** [comment]
[Poll](http://etc.ch/v243)
Please vote on this poll.

**Comment by b-beri** [comment]
The issue has been addressed with numbering starting from 0..... (As per the majority vote of 5-1 by the team).
